[pytest]
# --- ¡AQUÍ ESTÁ LA CORRECCIÓN! ---
# Apuntamos a la nueva ubicación del archivo de settings, que ahora
# está dentro del paquete 'project_config'.
DJANGO_SETTINGS_MODULE = project_config.settings

# Esta línea no necesita cambios. Le dice a pytest qué archivos
# debe considerar como archivos de test.
python_files = tests.py test_*.py *_tests.py

# --- ¡AÑADIDO ESENCIAL PARA LA ESTRUCTURA 'src/'! ---
# Le decimos a pytest que debe añadir el directorio 'src/' a su ruta
# de búsqueda para poder encontrar 'project_config' y 'corelab'.
pythonpath = src