# Generated by Django 5.2.7 on 2025-11-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("densidad", models.FloatField()),
                ("modulo_elasticidad", models.FloatField()),
                ("limite_elastico", models.FloatField()),
                ("resistencia_traccion", models.FloatField()),
                ("dureza", models.FloatField()),
            ],
        ),
    ]
