# Generated by Django 5.2.7 on 2025-11-07 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="densidad",
        ),
        migrations.RemoveField(
            model_name="material",
            name="dureza",
        ),
        migrations.RemoveField(
            model_name="material",
            name="limite_elastico",
        ),
        migrations.RemoveField(
            model_name="material",
            name="modulo_elasticidad",
        ),
        migrations.RemoveField(
            model_name="material",
            name="resistencia_traccion",
        ),
        migrations.AlterField(
            model_name="material",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name="Resultado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiempo", models.FloatField()),
                ("esfuerzo", models.FloatField()),
                ("deformacion", models.FloatField()),
                ("temperatura", models.FloatField(blank=True, null=True)),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resultados",
                        to="materials.material",
                    ),
                ),
            ],
        ),
    ]
