# Generated by Django 5.2.7 on 2025-11-07 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_remove_material_densidad_remove_material_dureza_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultado",
            name="material",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="materials.material"
            ),
        ),
        migrations.AlterField(
            model_name="resultado",
            name="tiempo",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
