# Generated by Django 5.2.7 on 2025-11-19 23:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ensayo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("metales", "Metales"),
                            ("polimericos", "Poliméricos"),
                            ("ceramicos", "Cerámicos"),
                            ("compuestos", "Compuestos"),
                        ],
                        default="metales",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Simulacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resultados", models.JSONField(default=dict)),
                (
                    "fecha_creacion",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "ensayo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="corelab.ensayo"
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="corelab.material",
                    ),
                ),
            ],
        ),
    ]
