# Generated by Django 5.2.7 on 2025-11-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core_lab", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="material",
            name="descripcion",
        ),
        migrations.AddField(
            model_name="material",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("metales", "Metales"),
                    ("polimericos", "Poliméricos"),
                    ("ceramicos", "Cerámicos"),
                    ("compuestos", "Compuestos"),
                ],
                default="metales",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="material",
            name="nombre",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
